language: python
python:
  - 2.7
install: 
  - python setup.py install
script:
  - python setup.py test
before_script:
  - cp ./config.ini.template ./config.ini
env:
  - PROCESSING_SETTINGS_FILE = ./config.ini